using Domain.Common;
using Domain.Documents.Enums;
using Domain.Documents.ValueObjects;

namespace Domain.Documents;

/// <summary>
///     Represents the document domain model.
/// </summary>
public sealed class Document : AuditableEntity
{
    /// <summary>
    ///     Initializes a new instance of the Document class for persistence.
    /// </summary>
    private Document()
    {
    }

    /// <summary>
    ///     Initializes a new instance of the Document class.
    /// </summary>
    public Document(
        Guid id,
        DocumentType type,
        FileMetadata metadata,
        FileHash? fileHash,
        DocumentParent parent,
        DateTimeOffset uploadedAt,
        Guid? uploadedByUserId,
        bool generatedBySystem = false)
        : base(id, uploadedAt, uploadedByUserId)
    {
        Type = type;
        Metadata = metadata;
        FileHash = fileHash;
        EquipmentId = parent.EquipmentId;
        ServiceReportId = parent.ServiceReportId;
        MaintenanceId = parent.MaintenanceId;
        IssueId = parent.IssueId;
        WorkSheetId = parent.WorkSheetId;
        GeneratedBySystem = generatedBySystem;
        UploadedAt = uploadedAt;
        UploadedByUserId = uploadedByUserId;

        ValidateSingleParent();
    }

    /// <summary>
    ///     Gets the type value.
    /// </summary>
    public DocumentType Type { get; private set; }

    /// <summary>
    ///     Gets the metadata value.
    /// </summary>
    public FileMetadata Metadata { get; private set; } = null!;

    /// <summary>
    ///     Gets the file hash value.
    /// </summary>
    public FileHash? FileHash { get; private set; }

    /// <summary>
    ///     Gets the title value.
    /// </summary>
    public string? Title { get; private set; }

    /// <summary>
    ///     Gets the description value.
    /// </summary>
    public string? Description { get; private set; }

    /// <summary>
    ///     Gets the equipment id value.
    /// </summary>
    public Guid? EquipmentId { get; }

    /// <summary>
    ///     Gets the service report id value.
    /// </summary>
    public Guid? ServiceReportId { get; }

    /// <summary>
    ///     Gets the maintenance id value.
    /// </summary>
    public Guid? MaintenanceId { get; }

    /// <summary>
    ///     Gets the issue id value.
    /// </summary>
    public Guid? IssueId { get; }

    /// <summary>
    ///     Gets the work sheet id value.
    /// </summary>
    public Guid? WorkSheetId { get; }

    /// <summary>
    ///     Gets the generated by system value.
    /// </summary>
    public bool GeneratedBySystem { get; private set; }

    /// <summary>
    ///     Gets the document version value.
    /// </summary>
    public int? DocumentVersion { get; private set; }

    /// <summary>
    ///     Gets the uploaded at value.
    /// </summary>
    public DateTimeOffset UploadedAt { get; private set; }

    /// <summary>
    ///     Gets the uploaded by user id value.
    /// </summary>
    public Guid? UploadedByUserId { get; private set; }

    /// <summary>
    ///     Gets the deleted at value.
    /// </summary>
    public DateTimeOffset? DeletedAt { get; private set; }

    /// <summary>
    ///     Gets the deleted by user id value.
    /// </summary>
    public Guid? DeletedByUserId { get; private set; }

    /// <summary>
    ///     Executes the describe domain operation.
    /// </summary>
    public void Describe(string? title, string? description, int? documentVersion, Guid? updatedByUserId,
        DateTimeOffset updatedAt)
    {
        Title = Optional(title);
        Description = Optional(description);
        DocumentVersion = documentVersion;
        MarkUpdated(updatedByUserId, updatedAt);
    }

    /// <summary>
    ///     Executes the delete domain operation.
    /// </summary>
    public void Delete(Guid? deletedByUserId, DateTimeOffset deletedAt)
    {
        DeletedAt = deletedAt;
        DeletedByUserId = deletedByUserId;
        MarkUpdated(deletedByUserId, deletedAt);
    }

    /// <summary>
    ///     Executes the validate single parent domain operation.
    /// </summary>
    private void ValidateSingleParent()
    {
        var parentCount =
            new[] { EquipmentId, ServiceReportId, MaintenanceId, IssueId, WorkSheetId }.Count(id =>
                id.HasValue && id.Value != Guid.Empty);
        if (parentCount != 1) throw new DomainException("A document must belong to exactly one parent entity.");
    }

    /// <summary>
    ///     Executes the optional domain operation.
    /// </summary>
    private static string? Optional(string? value)
    {
        return string.IsNullOrWhiteSpace(value) ? null : value.Trim();
    }
}

/// <summary>
///     Represents the document parent domain event data.
/// </summary>
public sealed record DocumentParent(
    Guid? EquipmentId = null,
    Guid? ServiceReportId = null,
    Guid? MaintenanceId = null,
    Guid? IssueId = null,
    Guid? WorkSheetId = null);